#! /bin/bash
SESSION="s-$TSN"

tmux -2 new-session -d -s $SESSION

# Setup a window for tailing log files
tmux new-window -t $SESSION:1 -n 'BELogs'
tmux split-window -h
tmux select-pane -t 0
tmux send-keys "$TSN" C-m
tmux send-keys "echo $PRE" C-m
tmux send-keys "ssh1 be-01" C-m
tmux send-keys "lesslogb" C-m
tmux select-pane -t 1
tmux send-keys "$TSN" C-m
tmux send-keys "echo $PRE" C-m
tmux send-keys "ssh1 be-02" C-m
tmux send-keys "lesslogp" C-m


tmux new-window -t $SESSION:2 -n 'DELogs'
tmux split-window -h
tmux select-pane -t 0
tmux send-keys "$TSN" C-m
tmux send-keys "echo $PRE" C-m
tmux send-keys "ssh1 de-01" C-m
tmux send-keys "cddlog" C-m
tmux select-pane -t 1
tmux send-keys "$TSN" C-m
tmux send-keys "echo $PRE" C-m
tmux send-keys "ssh1 de-02" C-m
tmux send-keys "cddlog" C-m

#tmux split-window -v
#tmux resize-pane -D 20
#tmux send-keys "tail -f /vagrant/maximus-mojo.log" C-m
# Setup a CoffeeScript compiler/watchdog pane
#tmux select-pane -t 0
#tmux split-window -v
#tmux resize-pane -D 20
#tmux send-keys "coffee -o /vagrant/root/static/js/ -cw /vagrant/root/coffee/" C-m

# Setup a NMON  window
tmux new-window -t $SESSION:3 -n 'NMON' 
tmux split-window -h
tmux split-window -v

tmux select-pane -t 0
tmux send-keys "$TSN" C-m
tmux send-keys "ssh1 be-01" C-m
tmux send-keys "nmon" C-m
tmux send-keys "cmn" C-m

tmux select-pane -t 0
tmux split-window -v
tmux send-keys "$TSN" C-m
tmux send-keys "ssh1 be-02" C-m
tmux send-keys "nmon" C-m
tmux send-keys "cmn" C-m

tmux select-pane -t 2
tmux send-keys "$TSN" C-m
tmux send-keys "ssh1 de-01" C-m
tmux send-keys "nmon" C-m
tmux send-keys "cmn" C-m


tmux select-pane -t 3
tmux send-keys "$TSN" C-m
tmux send-keys "ssh1 de-02" C-m
tmux send-keys "nmon" C-m
tmux send-keys "cmn" C-m

# Set default window
tmux select-window -t $SESSION:3

# Attach to session
tmux -2 attach-session -t $SESSION

